<?php

// autoload_files.php @generated by Composer

$vendorDir = dirname(dirname(__FILE__));
$baseDir = dirname(dirname($vendorDir)).'/mediawiki';

return array(
    'a24b5daa493ecb5e767c7d1592a8da36' => $vendorDir . '/mediawiki/at-ease/src/Functions.php',
    '05b0450c00f5832f7c71224e1a14593d' => $baseDir . '/extensions/ParserHooks/ParserHooks.php',
    '6fc53dfc4528cd3bf91e49f2f131294f' => $baseDir . '/extensions/SubPageList/SubPageList.php',
);
