<?php

// autoload_classmap.php @generated by Composer

$vendorDir = dirname(dirname(__FILE__));
$baseDir = dirname(dirname($vendorDir)).'/extensions/ParserHooks';

return array(
    'Comparable' => $vendorDir . '/data-values/data-values/src/interfaces/Comparable.php',
    'Copyable' => $vendorDir . '/data-values/data-values/src/interfaces/Copyable.php',
    'DataValues\\Tests\\DataValueTest' => $vendorDir . '/data-values/data-values/tests/phpunit/DataValueTest.php',
    'Hashable' => $vendorDir . '/data-values/data-values/src/interfaces/Hashable.php',
    'Immutable' => $vendorDir . '/data-values/data-values/src/interfaces/Immutable.php',
    'ParamProcessor\\Tests\\Definitions\\NumericParamTest' => $vendorDir . '/param-processor/param-processor/tests/phpunit/Definitions/NumericParamTest.php',
    'ParamProcessor\\Tests\\Definitions\\ParamDefinitionTest' => $vendorDir . '/param-processor/param-processor/tests/phpunit/Definitions/ParamDefinitionTest.php',
    'ParserHook' => $vendorDir . '/mediawiki/validator/src/legacy/ParserHook.php',
    'ParserHookCaller' => $vendorDir . '/mediawiki/validator/src/legacy/ParserHook.php',
    'ValueFormatters\\Test\\ValueFormatterTestBase' => $vendorDir . '/data-values/interfaces/tests/ValueFormatters/ValueFormatterTestBase.php',
    'ValueParsers\\Test\\BoolParserTest' => $vendorDir . '/data-values/common/tests/ValueParsers/BoolParserTest.php',
    'ValueParsers\\Test\\FloatParserTest' => $vendorDir . '/data-values/common/tests/ValueParsers/FloatParserTest.php',
    'ValueParsers\\Test\\IntParserTest' => $vendorDir . '/data-values/common/tests/ValueParsers/IntParserTest.php',
    'ValueParsers\\Test\\NullParserTest' => $vendorDir . '/data-values/common/tests/ValueParsers/NullParserTest.php',
    'ValueParsers\\Test\\StringValueParserTest' => $vendorDir . '/data-values/common/tests/ValueParsers/StringValueParserTest.php',
    'ValueParsers\\Test\\ValueParserTestBase' => $vendorDir . '/data-values/common/tests/ValueParsers/ValueParserTestBase.php',
);
