<?php

// autoload_psr4.php @generated by Composer

$vendorDir = dirname(dirname(__FILE__));
$baseDir = dirname(dirname($vendorDir)).'/extensions/ParserHooks';

return array(
    'ValueValidators\\' => array($vendorDir . '/data-values/validators/src'),
    'ParserHooks\\' => array($baseDir . '/src'),
    'ParamProcessor\\' => array($vendorDir . '/param-processor/param-processor/src', $vendorDir . '/mediawiki/validator/src/ParamProcessor'),
);
