<?php

// autoload_psr4.php @generated by Composer

$vendorDir = dirname(dirname(__FILE__));
$baseDir = dirname(dirname($vendorDir)).'/extensions/SyntaxHighlight_GeSHi';

return array(
    'Symfony\\Component\\Process\\' => array($vendorDir . '/symfony/process'),
);
