<?php

// autoload_files.php @generated by Composer

$vendorDir = dirname(dirname(__FILE__));
$baseDir = dirname($vendorDir).'/mediawiki';

return array(
    'd1715cacc3c23b16a030645514266a76' => $vendorDir . '/data-values/interfaces/Interfaces.php',
    '7cb394c3af2b1ae832979b0368e0da62' => $vendorDir . '/data-values/data-values/DataValues.php',
    '0dd9431cbbfa9ed9cb9d565d7129dbaf' => $vendorDir . '/data-values/validators/Validators.php',
    '90559502573a0d473dc66fde5c0ff7e2' => $vendorDir . '/data-values/common/Common.php',
    'af3cc937b8a54e5b4209c82d6cfe8889' => $vendorDir . '/param-processor/param-processor/DefaultConfig.php',
    'a24b5daa493ecb5e767c7d1592a8da36' => $vendorDir . '/mediawiki/at-ease/src/Functions.php',
    'c3ae67574219cc56cab6c30ef8877b85' => $baseDir . '/extensions/Validator/Validator.php',
    '94e265ce14c952a920a4ea5f7e8e9baa' => $vendorDir . '/mediawiki/parser-hooks/ParserHooks.php',
    '05b0450c00f5832f7c71224e1a14593d' => $baseDir . '/extensions/ParserHooks/ParserHooks.php',
    '6fc53dfc4528cd3bf91e49f2f131294f' => $baseDir . '/extensions/SubPageList/SubPageList.php',
    'f26670cddfc4393aed525353f362633e' => $baseDir . '/extensions/Validator/Validator.php',
);
